server:
  port: 8080
  contextPath: /telescope
  tomcat:
    uri-encoding: utf-8

spring:
  thymeleaf:
    mode: LEGACYHTML5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  session:
    store-type: none

  devtools:
    restart:
      enabled: true
